### ISSUE TITLE
Migrate to NET5 

### ISSUE THREAD

**Issue by Fma965** [CyanLabs/Syn3Updater#36]
Move to Net5 to allow for potentially easier migration to cross platform in the future

**Comment by Fma965** [comment]
AFAIK this technically works on NET5 @bakedpatato ?

1 thing to note is the 25MB DLL that is needed for API calls though, would need to re-work my update system to exclude redownloading that each time i think.

**Comment by bakedpatato** [comment]
Yep, the app runs fine in Win10 only, and yeah I think it would be smart to exclude based on a signature overwriting DLLs.

Before switching to net5 we would either have to switch to a ["self-contained" app ](https://docs.microsoft.com/en-us/dotnet/core/deploying/#publish-self-contained) (increasing the file size more of course) , tell users to download the net5 runtime, or tell users that they'll have to use a installer (so that the installer would install the runtime)

Plus given how net6 is coming out soon I think before doing any  of that we should wait for net6 to go RTM 😄

**Comment by Fma965** [comment]
Oh right, well lets wait for NET6 then :) i'll close this for now ;)
